=== AgaDufrat/govuk-content-schemas/formats/redirect/publisher/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "publishing_app",
    "redirects",
    "base_path",
    "content_id"
  ],
  "properties": {
    "base_path": {
      "$ref": "#/definitions/absolute_path"
    },
    "content_id": {
      "$ref": "#/definitions/guid"
    },
    "format": {
      "description": "DEPRECATED: This field will be removed by Tijmen.",
      "enum": [ "redirect" ]
    },
    "document_type": {
      "enum": [ "redirect" ]
    },
    "schema_name": {
      "enum": [ "redirect" ]
    },
    "publishing_app": {
      "$ref": "#/definitions/publishing_app"
    },
    "update_type": {
      "enum": [ "major", "minor", "republish" ]
    },
    "redirects": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "path",
          "type",
          "destination"
        ],
        "properties": {
          "path": {
            "$ref": "#/definitions/absolute_path"
          },
          "type": {
            "enum": [ "prefix", "exact" ]
          },
          "destination": {
            "$ref": "#/definitions/absolute_fullpath"
          },
          "segments_mode": {
            "enum": [ "preserve", "ignore" ],
            "description": "For prefix redirects, preserve or ignore the rest of the fullpath. For exact, preserve or ignore the querystring."
          }
        }
      }
    }
  },
  "definitions": {
    "absolute_path": {
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?$",
      "description": "A path only. Query string and/or fragment are not allowed."
    },
    "absolute_fullpath": {
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?(\\?([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)?(#([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)?$",
      "description": "A path with optional query string and/or fragment."
    },
    "guid": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "guid_list": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/guid"
      }
    },
    "publishing_app": {
      "description": "The application that owns this content item. Should be the hostname of the application creating it.",
      "type": "string",
      "enum": ["businesssupportfinder", "calculators", "calendars", "collections-publisher", "contacts", "content-tagger", "design-principles", "external-link-tracker", "feedback", "frontend", "govuk_content_api", "hmrc-manuals-api", "info-frontend", "licencefinder", "manuals-frontend", "manuals-publisher", "performanceplatform-big-screen-view", "policy-publisher", "publisher", "rummager", "service-manual-publisher", "share-sale-publisher", "short-url-manager", "smartanswers", "specialist-publisher", "spotlight", "static", "tariff", "travel-advice-publisher", "whitehall"]
    }
  }
}

=== AgaDufrat/govuk-content-schemas/formats/redirect/publisher/examples/redirect-with-replacement.json
{
  "content_id": "f779f980-403d-473b-80aa-f038a58c3107",
  "base_path": "/406beacon",
  "publishing_app": "short-url-manager",
  "update_type": "minor",
  "redirects": [
    {
      "path": "/406beacon",
      "type": "exact",
      "destination": "/maritime-safety-weather-and-navigation/register-406-mhz-beacons?query=answer#fragment"
    }
  ],
  "document_type": "redirect",
  "schema_name": "redirect"
}
