=== AgaDufrat/govuk-content-schemas/formats/unpublishing/frontend/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "base_path",
    "format",
    "locale"
  ],
  "properties": {
    "base_path": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "format": {
      "type": "string",
      "enum": [
        "unpublishing"
      ]
    },
    "public_updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "locale": {
      "type": "string"
    },
    "need_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "details": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "unpublished_at"
      ],
      "properties": {
        "explanation": {
          "type": [
            "string",
            "null"
          ]
        },
        "unpublished_at": {
          "type": "string",
          "format": "date-time"
        },
        "alternative_url": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        }
      }
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "links": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "available_translations": {
          "$ref": "#/definitions/frontend_links"
        }
      }
    }
  },
  "definitions": {
    "route": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "type"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        }
      }
    },
    "frontend_links": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "title": {
            "type": "string"
          },
          "base_path": {
            "type": "string"
          },
          "api_url": {
            "type": "string",
            "format": "uri"
          },
          "web_url": {
            "type": "string",
            "format": "uri"
          },
          "locale": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== AgaDufrat/govuk-content-schemas/formats/unpublishing/frontend/examples/unpublishing.json
{
  "base_path":"/government/case-studies/bubble-trouble",
  "title":"Bubble and trouble",
  "description":"A case study about bubble and trouble.",
  "format":"unpublishing",
  "need_ids":[

  ],
  "locale":"en",
  "updated_at":"2014-12-10T14:50:13.372Z",
  "public_updated_at":"2014-04-30T23:01:51.000+00:00",
  "details":{
    "explanation": "This is now redundant",
    "unpublished_at":"2014-05-01T14:59:17+01:00",
    "alternative_url": null
  },
  "links":{
    "available_translations":[
      {
        "title":"Bubble and trouble",
        "base_path":"/government/case-studies/bubble-trouble",
        "api_url":"http://content-store/content/government/case-studies/bubble-trouble",
        "web_url":"https://www.gov.uk/government/case-studies/bubble-trouble",
        "locale":"en"
      }
    ]
  }
}
