=== AgaDufrat/govuk-content-schemas/dist/formats/topic/frontend/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "base_path",
    "format",
    "locale",
    "public_updated_at"
  ],
  "properties": {
    "base_path": {
      "$ref": "#/definitions/absolute_path"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "format": {
      "type": "string",
      "enum": [
        "topic"
      ]
    },
    "public_updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "locale": {
      "type": "string"
    },
    "need_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "details": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "beta": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "groups": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "name",
              "contents"
            ],
            "properties": {
              "name": {
                "type": "string"
              },
              "contents": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "links": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "parent": {
          "$ref": "#/definitions/frontend_links"
        },
        "children": {
          "$ref": "#/definitions/frontend_links"
        },
        "available_translations": {
          "$ref": "#/definitions/frontend_links"
        }
      }
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    }
  },
  "definitions": {
    "absolute_path": {
      "type": "string",
      "pattern": "^/(([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})+(/([a-zA-Z0-9._~!$&'()*+,;=:@-]|%[0-9a-fA-F]{2})*)*)?$"
    },
    "route": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "type"
      ],
      "properties": {
        "path": {
          "type": "string"
        },
        "type": {
          "enum": [
            "prefix",
            "exact"
          ]
        }
      }
    },
    "guid_list": {
      "type": "array",
      "items": {
        "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$"
      }
    },
    "frontend_links": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "title",
          "base_path",
          "locale"
        ],
        "properties": {
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "base_path": {
            "type": "string"
          },
          "api_url": {
            "type": "string",
            "format": "uri"
          },
          "web_url": {
            "type": "string",
            "format": "uri"
          },
          "locale": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== AgaDufrat/govuk-content-schemas/formats/topic/frontend/examples/topic-in-beta.json
{
    "base_path": "/topic/oil-and-gas-beta",
    "description": "",
    "details": {
      "beta": true
    },
    "format": "topic",
    "links": {
      "children": []
    },
    "locale": "en",
    "need_ids": [],
    "public_updated_at": "2015-04-20T15:46:10.000+00:00",
    "title": "Oil and gas",
    "updated_at": "2015-04-20T15:50:11.000+00:00"
}

=== AgaDufrat/govuk-content-schemas/formats/topic/frontend/examples/curated_subtopic.json
{
    "base_path": "/topic/oil-and-gas/offshore",
    "description": "A page about offshore oil and gas",
    "details": {
      "groups": [
        {
          "name": "Oil rigs",
          "contents": [
            "/oil-rig-safety-requirements",
            "/oil-rig-staffing"
          ]
        },
        {
          "name": "Piping",
          "contents": [
            "/undersea-piping-restrictions"
          ]
        }
      ]
    },
    "format": "topic",
    "links": {
      "parent": [
        {
          "base_path": "/topic/oil-and-gas",
          "title": "Oil and gas",
          "api_url": "https://www.gov.uk/api/content/topic/oil-and-gas",
          "web_url": "https://www.gov.uk/topic/oil-and-gas",
          "locale": "en"
        }
      ]
    },
    "locale": "en",
    "need_ids": [],
    "public_updated_at": "2015-04-20T15:46:10.000+00:00",
    "title": "Offshore",
    "updated_at": "2015-04-20T15:50:11.000+00:00"
}

=== AgaDufrat/govuk-content-schemas/formats/topic/frontend/examples/uncurated_subtopic.json
{
    "base_path": "/topic/oil-and-gas/licensing",
    "description": "A page about oil and gas licensing",
    "details": {
    },
    "format": "topic",
    "links": {
      "parent": [
        {
          "base_path": "/topic/oil-and-gas",
          "title": "Oil and gas",
          "api_url": "https://www.gov.uk/api/content/topic/oil-and-gas",
          "web_url": "https://www.gov.uk/topic/oil-and-gas",
          "locale": "en"
        }
      ]
    },
    "locale": "en",
    "need_ids": [],
    "public_updated_at": "2015-04-20T15:46:10.000+00:00",
    "title": "Oil and gas: Licensing",
    "updated_at": "2015-04-20T15:50:11.000+00:00"
}
